pipeline {
    agent any

    stages {

        stage('Install Dependencies') {
            steps {
                dir('parabank-playwright') {
                    bat 'npm ci'
                }
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                dir('parabank-playwright') {
                    bat 'npx playwright install chromium --with-deps'
                }
            }
        }

        stage('Run Tests') {
            steps {
                dir('parabank-playwright') {
                    bat 'npm run full'
                }
            }
        }

        stage('Generate Allure Report') {
            steps {
                dir('parabank-playwright') {
                    bat 'npx allure-commandline generate allure-results --clean -o allure-report'
                }
            }
        }
    }

    post {
        always {
            allure([
                results: [[path: 'parabank-playwright/allure-results']]
            ])
        }
    }
}